In [ ]:
! pip install ctgan

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ctgan in /usr/local/lib/python3.10/dist-packages (0.7.3)
Requirement already satisfied: packaging<22,>=20 in /usr/local/lib/python3.10/dist-packages (from ctgan) (21.3)
Requirement already satisfied: rdt<2.0,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.4.2)
Requirement already satisfied: numpy<2,>=1.23.3 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.24.3)
Requirement already satisfied: pandas>=1.3.4 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.5.3)
Requirement already satisfied: scikit-learn<2,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from ctgan) (1.2.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from ctgan) (2.0.1+cu118)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from packaging<22,>=20->ctgan) (3.0.9)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.4->ctgan) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.4->ctgan) (2022.7.1)
Requirement already satisfied: psutil<6,>=5.7 in /usr/local/lib/python3.10/dist-packages (from rdt<2.0,>=1.3.0->ctgan) (5.9.5)
Requirement already satisfied: Faker>=10 in /usr/local/lib/python3.10/dist-packages (from rdt<2.0,>=1.3.0->ctgan) (18.9.0)
Requirement already satisfied: scipy<2,>=1.9.2 in /usr/local/lib/python3.10/dist-packages (from rdt<2.0,>=1.3.0->ctgan) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1.1.3->ctgan) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn<2,>=1.1.3->ctgan) (3.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.12.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.11.0->ctgan) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.11.0->ctgan) (16.0.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.3.4->ctgan) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->ctgan) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->ctgan) (1.3.0)

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/Shareddrives/BAX423/Project/Data generation/datageneration.csv')
df

,Date,Active Energy (kcal),Alcohol Consumption (count),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Apple Stand Hour (count),Apple Stand Time (min),Basal Body Temperature (degF),Basal Energy Burned (kcal),Blood Alcohol Content (%),...,Waist Circumference (in),Walking + Running Distance (mi),Walking Asymmetry Percentage (%),Walking Double Support Percentage (%),Walking Heart Rate Average (count/min),Walking Speed (mi/hr),Walking Step Length (in),Weight & Body Mass (lb),Wheelchair Distance (mi),Zinc (mg)
0,9/11/22 0:00,25.480,NaN,NaN,NaN,NaN,NaN,NaN,683.88,NaN,...,NaN,1.260,0.00,25.60,NaN,3.10,27.65,NaN,NaN,
1,9/12/22 0:00,16.640,NaN,NaN,NaN,NaN,NaN,NaN,1271.00,NaN,...,NaN,0.467,0.00,24.91,NaN,3.35,27.47,NaN,NaN,
2,9/13/22 0:00,24.700,NaN,NaN,NaN,NaN,NaN,NaN,1272.00,NaN,...,NaN,0.548,0.00,23.22,NaN,3.88,30.91,NaN,NaN,
3,9/14/22 0:00,41.720,NaN,NaN,NaN,NaN,NaN,NaN,1271.00,NaN,...,NaN,0.856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,9/15/22 0:00,33.890,NaN,NaN,NaN,NaN,NaN,NaN,1272.00,NaN,...,NaN,0.760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,5/3/23 0:00,167.150,NaN,15.0,NaN,NaN,42.0,NaN,1371.00,NaN,...,NaN,1.310,3.75,27.64,NaN,2.63,24.60,NaN,NaN,
235,5/4/23 0:00,0.148,NaN,NaN,NaN,NaN,NaN,NaN,309.34,NaN,...,NaN,3.200,0.30,24.74,NaN,3.21,28.20,NaN,NaN,
236,5/5/23 0:00,95.830,NaN,3.0,96.83,NaN,14.0,NaN,715.94,NaN,...,NaN,0.940,3.75,27.73,99.5,2.70,24.69,NaN,NaN,
237,5/6/23 0:00,133.220,NaN,7.0,NaN,NaN,52.0,NaN,1051.00,NaN,...,NaN,0.998,0.00,26.33,105.0,2.90,25.98,NaN,NaN,
238,5/7/23 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.425,0.00,22.54,NaN,3.59,29.70,NaN,NaN,

In [ ]:
new_cols = ['Active Energy (kcal)', 'Apple Exercise Time (min)',
       'Apple Sleeping Wrist Temperature (degF)', 'Basal Energy Burned (kcal)',
       'Blood Oxygen Saturation (%)', 'Heart Rate [Min] (count/min)', \
       'Heart Rate [Max] (count/min)', 'Heart Rate [Avg] (count/min)', \
       'Heart Rate Variability (ms)', 'Respiratory Rate (count/min)',\
       'Resting Heart Rate (count/min)', 'Sleep Analysis [In Bed] (hr)',\
       'Sleep Analysis [Core] (hr)', 'Sleep Analysis [Deep] (hr)', \
       'Sleep Analysis [REM] (hr)', 'Sleep Analysis [Awake] (hr)', \
       'Step Count (count)', 'Walking Heart Rate Average (count/min)']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_new = df[new_cols]

In [ ]:
df_new=df_new.dropna(axis=0,how='any')

In [ ]:
df_new

,Active Energy (kcal),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Basal Energy Burned (kcal),Blood Oxygen Saturation (%),Heart Rate [Min] (count/min),Heart Rate [Max] (count/min),Heart Rate [Avg] (count/min),Heart Rate Variability (ms),Respiratory Rate (count/min),Resting Heart Rate (count/min),Sleep Analysis [In Bed] (hr),Sleep Analysis [Core] (hr),Sleep Analysis [Deep] (hr),Sleep Analysis [REM] (hr),Sleep Analysis [Awake] (hr),Step Count (count),Walking Heart Rate Average (count/min)
20,198.38,12.0,96.94,1342.0,97.00,54.0,111.0,78.44,48.06,24.11,61.0,5.330952,0.000000,0.000000,0.000000,0.000000,4688,97.0
21,449.14,47.0,97.06,1396.0,94.50,55.0,153.0,87.26,52.47,18.42,59.0,7.299428,3.658333,0.600000,1.233333,4.141667,7659,111.0
22,127.40,6.0,96.96,1322.0,96.73,52.0,113.0,68.61,56.97,17.24,61.0,7.382358,4.491667,1.075000,1.775000,0.191667,2823,100.5
23,315.79,35.0,97.02,1369.0,94.83,54.0,117.0,69.40,43.90,17.17,60.0,7.508639,4.475000,0.825000,1.900000,0.100000,7323,109.0
24,302.22,36.0,97.21,1345.0,96.40,48.0,131.0,70.56,53.03,17.53,55.0,7.064752,3.683333,0.908333,1.875000,0.075000,7904,115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,140.47,14.0,97.29,1345.0,98.00,54.0,121.0,81.07,30.50,18.07,70.0,7.400460,0.000000,0.000000,0.000000,0.000000,4547,88.0
194,183.39,13.0,96.43,1369.0,99.00,47.0,114.0,86.81,33.52,24.50,76.0,7.208527,0.000000,0.000000,0.000000,0.000000,5284,106.5
202,564.84,104.0,97.46,1383.0,99.67,48.0,183.0,101.82,40.30,17.61,80.0,7.518443,2.866667,0.600000,0.800000,0.275000,13992,102.5
208,249.42,16.0,97.32,1382.0,97.33,54.0,103.0,72.11,41.73,17.40,63.0,8.166667,5.708333,0.508333,1.950000,0.233333,6932,96.0
221,292.26,44.0,97.62,1394.0,98.00,44.0,148.0,92.71,36.88,19.50,70.0,6.960686,0.000000,0.000000,0.000000,0.000000,8104,132.0

In [ ]:
df_new.describe()

,Active Energy (kcal),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Basal Energy Burned (kcal),Blood Oxygen Saturation (%),Heart Rate [Min] (count/min),Heart Rate [Max] (count/min),Heart Rate [Avg] (count/min),Heart Rate Variability (ms),Respiratory Rate (count/min),Resting Heart Rate (count/min),Sleep Analysis [In Bed] (hr),Sleep Analysis [Core] (hr),Sleep Analysis [Deep] (hr),Sleep Analysis [REM] (hr),Sleep Analysis [Awake] (hr),Step Count (count),Walking Heart Rate Average (count/min)
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.00000,80.000000
mean,236.408875,21.725000,97.336125,1377.775000,97.116625,51.621250,133.775000,77.286875,44.501375,18.146625,61.681250,7.519306,3.367813,0.557708,1.330000,0.257917,4710.47500,109.587500
std,81.220981,21.412746,0.555455,26.799761,1.262855,4.703101,21.148047,7.275378,9.793909,1.745562,5.868951,1.145748,2.016680,0.377130,0.835804,0.566823,2670.74912,11.367502
min,120.670000,1.000000,95.730000,1305.000000,92.600000,41.000000,97.000000,65.420000,27.950000,16.150000,52.000000,5.330952,0.000000,0.000000,0.000000,0.000000,1305.00000,82.500000
25%,181.247500,7.750000,96.955000,1357.000000,96.550000,48.000000,118.000000,72.242500,37.800000,17.192500,58.000000,6.960355,2.743750,0.283333,0.843750,0.014583,2735.00000,102.375000
50%,219.770000,12.000000,97.315000,1383.000000,97.365000,52.000000,128.500000,74.970000,42.620000,17.755000,60.000000,7.469673,3.904167,0.612500,1.537500,0.091667,3888.00000,109.500000
75%,293.140000,35.250000,97.750000,1397.000000,97.955000,54.000000,145.000000,80.475000,49.400000,18.297500,64.250000,7.830116,4.618750,0.818750,1.950000,0.237500,6524.00000,115.000000
max,564.840000,104.000000,98.410000,1434.000000,100.000000,63.000000,183.000000,101.820000,73.770000,24.500000,80.000000,14.597087,7.866667,1.266667,2.500000,4.141667,13992.00000,144.000000

In [ ]:
from ctgan import CTGAN

In [ ]:
ctgan = CTGAN(epochs=10)
ctgan.fit(df_new)

In [ ]:
synthetic_df = ctgan.sample(200000)
synthetic_df.head()

,Active Energy (kcal),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Basal Energy Burned (kcal),Blood Oxygen Saturation (%),Heart Rate [Min] (count/min),Heart Rate [Max] (count/min),Heart Rate [Avg] (count/min),Heart Rate Variability (ms),Respiratory Rate (count/min),Resting Heart Rate (count/min),Sleep Analysis [In Bed] (hr),Sleep Analysis [Core] (hr),Sleep Analysis [Deep] (hr),Sleep Analysis [REM] (hr),Sleep Analysis [Awake] (hr),Step Count (count),Walking Heart Rate Average (count/min)
0,328.152227,64.662530,98.942012,1420.105723,92.784332,46.663685,114.421848,94.565024,66.578288,20.982951,77.396915,7.106866,0.186247,0.445933,0.719166,1.776223,869,81.115780
1,243.789257,46.358476,96.141626,1393.224202,96.006480,55.890154,156.578754,84.260335,78.461164,18.290310,62.683869,8.078462,6.649334,1.452936,1.807182,1.342182,7126,126.626493
2,362.683856,26.665393,97.046610,1390.041438,94.264248,55.844043,122.855940,106.178376,58.517151,16.304507,52.944648,5.435509,2.892812,1.119136,1.761298,-0.105135,4621,108.182274
3,409.244080,159.888697,97.742957,1434.177582,96.127779,54.099530,108.296995,72.319027,74.546661,16.610726,56.891093,7.919901,5.876025,0.470247,1.065085,0.087355,1796,111.502363
4,803.119630,49.110832,96.678858,1402.490563,97.642443,61.954442,115.861748,74.313193,54.484240,15.154228,47.911219,17.454384,6.430451,1.187446,0.845427,-0.448804,8859,135.021707

In [ ]:
synthetic_df.describe()

,Active Energy (kcal),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Basal Energy Burned (kcal),Blood Oxygen Saturation (%),Heart Rate [Min] (count/min),Heart Rate [Max] (count/min),Heart Rate [Avg] (count/min),Heart Rate Variability (ms),Respiratory Rate (count/min),Resting Heart Rate (count/min),Sleep Analysis [In Bed] (hr),Sleep Analysis [Core] (hr),Sleep Analysis [Deep] (hr),Sleep Analysis [REM] (hr),Sleep Analysis [Awake] (hr),Step Count (count),Walking Heart Rate Average (count/min)
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,367.968259,70.419484,97.293904,1363.044099,96.137194,54.271098,138.359173,88.370525,61.592489,18.346889,57.448787,7.208902,2.822036,0.559379,0.911751,0.492872,6387.796060,111.751463
std,165.833303,45.878489,0.716788,35.682151,1.721918,6.214883,26.535669,9.781550,14.689065,2.477398,6.762795,2.192491,2.449345,0.469966,0.981606,1.069108,3998.766009,15.713203
min,-169.084622,-42.837169,95.274406,1265.382771,91.068715,34.149054,78.121394,56.742973,18.091167,11.891867,46.317841,-1.074465,-3.079594,-0.602276,-1.486095,-3.301565,-4837.000000,66.533516
25%,249.803862,26.609607,96.764817,1337.773581,94.862870,49.832674,118.868577,81.165281,51.434570,16.710138,52.402930,6.043318,0.757786,0.200826,0.133984,-0.048937,3439.000000,100.222222
50%,332.361944,66.489732,97.290538,1364.133876,96.235782,54.578273,135.250215,86.351082,59.770563,17.912654,56.099149,6.898209,3.071609,0.510158,0.973643,0.240053,5616.500000,112.181737
75%,442.182637,96.068372,97.818099,1389.259516,97.338460,58.990035,154.387130,96.130469,72.014859,19.557208,61.022715,7.898307,4.854285,0.942084,1.671848,0.808788,8986.000000,123.615455
max,1015.085948,186.916754,99.369167,1462.345205,101.828652,69.386740,221.072141,113.961126,98.103132,29.627112,88.496669,20.692041,8.128918,1.681269,3.398127,7.096846,22300.000000,152.230304

In [ ]:
final_df = synthetic_df[(synthetic_df > 0).all(1)]

In [ ]:
final_df = final_df[final_df['Heart Rate [Max] (count/min)'] < 170] 
final_df = final_df[final_df['Sleep Analysis [In Bed] (hr)'] < 10 ]
final_df = final_df[final_df['Blood Oxygen Saturation (%)'] < 100 ]
final_df = final_df[final_df['Walking Heart Rate Average (count/min)'] < 130 ]

In [ ]:
final_df.describe()

,Active Energy (kcal),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Basal Energy Burned (kcal),Blood Oxygen Saturation (%),Heart Rate [Min] (count/min),Heart Rate [Max] (count/min),Heart Rate [Avg] (count/min),Heart Rate Variability (ms),Respiratory Rate (count/min),Resting Heart Rate (count/min),Sleep Analysis [In Bed] (hr),Sleep Analysis [Core] (hr),Sleep Analysis [Deep] (hr),Sleep Analysis [REM] (hr),Sleep Analysis [Awake] (hr),Step Count (count),Walking Heart Rate Average (count/min)
count,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000,54876.000000
mean,368.639423,71.914171,97.378864,1363.949681,96.081877,54.182852,130.612551,88.407227,62.011866,18.346349,57.547538,6.655440,3.545820,0.658739,1.315379,0.862111,6470.632262,107.351771
std,165.492403,46.271575,0.710972,35.574411,1.674102,6.173191,19.297998,9.754254,14.684961,2.459661,6.782924,1.382120,1.944380,0.408946,0.733579,1.055335,3875.382557,13.399462
min,0.266460,0.021943,95.281790,1265.543886,91.068715,34.814469,78.292295,56.742973,18.436537,12.104231,46.442807,0.038531,0.000221,0.000076,0.000008,0.000006,1.000000,67.232809
25%,250.058177,26.870225,96.856863,1338.884967,94.818773,49.774184,116.326147,81.202668,51.833864,16.726045,52.500977,5.904705,1.891066,0.315770,0.730119,0.203420,3515.000000,97.646214
50%,333.125501,67.874220,97.385043,1365.267384,96.209982,54.449403,130.775694,86.410020,60.101173,17.918584,56.186002,6.697288,3.719603,0.591497,1.295401,0.488860,5646.000000,108.370008
75%,443.051810,98.808977,97.903588,1390.089712,97.294474,58.868129,145.085175,96.150738,72.961041,19.550198,61.107250,7.526439,5.101290,0.997918,1.871519,1.091722,8992.250000,118.220672
max,1007.366981,186.916754,99.334182,1462.345205,99.999808,69.386740,169.999950,113.961126,97.844636,29.627112,88.129291,9.999985,8.101267,1.681269,3.372634,7.096846,22185.000000,129.999434

In [ ]:
final_df

,Active Energy (kcal),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Basal Energy Burned (kcal),Blood Oxygen Saturation (%),Heart Rate [Min] (count/min),Heart Rate [Max] (count/min),Heart Rate [Avg] (count/min),Heart Rate Variability (ms),Respiratory Rate (count/min),Resting Heart Rate (count/min),Sleep Analysis [In Bed] (hr),Sleep Analysis [Core] (hr),Sleep Analysis [Deep] (hr),Sleep Analysis [REM] (hr),Sleep Analysis [Awake] (hr),Step Count (count),Walking Heart Rate Average (count/min)
0,328.152227,64.662530,98.942012,1420.105723,92.784332,46.663685,114.421848,94.565024,66.578288,20.982951,77.396915,7.106866,0.186247,0.445933,0.719166,1.776223,869,81.115780
1,243.789257,46.358476,96.141626,1393.224202,96.006480,55.890154,156.578754,84.260335,78.461164,18.290310,62.683869,8.078462,6.649334,1.452936,1.807182,1.342182,7126,126.626493
3,409.244080,159.888697,97.742957,1434.177582,96.127779,54.099530,108.296995,72.319027,74.546661,16.610726,56.891093,7.919901,5.876025,0.470247,1.065085,0.087355,1796,111.502363
6,305.060336,167.817428,96.366693,1385.219234,97.687709,53.925875,168.572321,87.243696,54.924087,16.263618,54.225402,7.517899,3.827422,0.533314,0.841712,0.768393,10123,95.591383
19,450.963332,131.891163,97.974060,1383.692113,97.009611,39.272461,152.030877,84.110661,59.718791,17.368921,75.938956,6.081991,5.760501,0.232981,1.137708,0.631911,1581,109.325529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199991,626.878233,128.377023,97.790068,1433.097089,96.887080,46.534712,141.169600,97.393184,48.090378,19.316498,49.084734,6.970393,2.998361,0.232240,2.360240,0.019987,4129,94.699896
199994,266.885511,64.938769,96.653273,1395.221430,98.594164,48.274081,149.311378,80.248108,80.928378,17.995739,65.868609,7.555832,4.898232,0.035647,1.220136,0.937936,5790,120.027743
199995,459.071612,86.186962,97.058131,1405.497756,96.123328,47.580753,161.819922,76.007294,62.991551,19.150072,51.190962,9.265638,3.109903,1.189349,2.323447,0.312050,5331,111.757992
199998,591.269895,67.766969,97.121751,1338.139733,94.066629,53.870823,137.629360,80.519405,61.268419,20.654465,60.497634,6.399830,4.152484,0.810712,2.824576,1.237931,4995,100.817426
199999,155.842883,78.678442,98.058880,1451.713328,96.569639,49.671690,143.810635,77.211153,58.975978,26.305580,59.883950,7.106849,3.485038,0.200829,0.907670,0.259007,14012,117.357797

In [ ]:
final_df.to_csv('final_analysis_df1')

In [ ]:
pd.read_csv('final_analysis_df1',)

,Unnamed: 0,Active Energy (kcal),Apple Exercise Time (min),Apple Sleeping Wrist Temperature (degF),Basal Energy Burned (kcal),Blood Oxygen Saturation (%),Heart Rate [Min] (count/min),Heart Rate [Max] (count/min),Heart Rate [Avg] (count/min),Heart Rate Variability (ms),Respiratory Rate (count/min),Resting Heart Rate (count/min),Sleep Analysis [In Bed] (hr),Sleep Analysis [Core] (hr),Sleep Analysis [Deep] (hr),Sleep Analysis [REM] (hr),Sleep Analysis [Awake] (hr),Step Count (count),Walking Heart Rate Average (count/min)
0,0,328.152227,64.662530,98.942012,1420.105723,92.784332,46.663685,114.421848,94.565024,66.578288,20.982951,77.396915,7.106866,0.186247,0.445933,0.719166,1.776223,869,81.115780
1,1,243.789257,46.358476,96.141626,1393.224202,96.006480,55.890154,156.578754,84.260335,78.461164,18.290310,62.683869,8.078462,6.649334,1.452936,1.807182,1.342182,7126,126.626493
2,3,409.244080,159.888697,97.742957,1434.177582,96.127779,54.099530,108.296995,72.319027,74.546661,16.610726,56.891093,7.919901,5.876025,0.470247,1.065085,0.087355,1796,111.502363
3,6,305.060336,167.817428,96.366693,1385.219234,97.687709,53.925875,168.572321,87.243696,54.924087,16.263618,54.225402,7.517899,3.827422,0.533314,0.841712,0.768393,10123,95.591383
4,19,450.963332,131.891163,97.974060,1383.692113,97.009611,39.272461,152.030877,84.110661,59.718791,17.368921,75.938956,6.081991,5.760501,0.232981,1.137708,0.631911,1581,109.325529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54871,199991,626.878233,128.377023,97.790068,1433.097089,96.887080,46.534712,141.169600,97.393184,48.090378,19.316498,49.084734,6.970393,2.998361,0.232240,2.360240,0.019987,4129,94.699896
54872,199994,266.885511,64.938769,96.653273,1395.221430,98.594164,48.274081,149.311378,80.248108,80.928378,17.995739,65.868609,7.555832,4.898232,0.035647,1.220136,0.937936,5790,120.027743
54873,199995,459.071612,86.186962,97.058131,1405.497756,96.123328,47.580753,161.819922,76.007294,62.991551,19.150072,51.190962,9.265638,3.109903,1.189349,2.323447,0.312050,5331,111.757992
54874,199998,591.269895,67.766969,97.121751,1338.139733,94.066629,53.870823,137.629360,80.519405,61.268419,20.654465,60.497634,6.399830,4.152484,0.810712,2.824576,1.237931,4995,100.817426
54875,199999,155.842883,78.678442,98.058880,1451.713328,96.569639,49.671690,143.810635,77.211153,58.975978,26.305580,59.883950,7.106849,3.485038,0.200829,0.907670,0.259007,14012,117.357797